laboratorna5shchedrov/Models/ErrorViewModel.cs
namespace laboratorna5shchedrov.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

laboratorna5shchedrov/Controllers/CookieController.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace laboratorna5shchedrov.Controllers
{
    public class CookieController : Controller
    {
        [HttpGet]
        public IActionResult SetCookie()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SetCookie(string value, DateTime expiryDate)
        {
            if (string.IsNullOrEmpty(value))
            {
                ModelState.AddModelError("", "value cant be empty");
                return View();
            }

            var options = new Microsoft.AspNetCore.Http.CookieOptions
            {
                Expires = expiryDate
            };

            Response.Cookies.Append("MyCookie", value, options);

            Response.Cookies.Append("MyCookieExpiry", expiryDate.ToString(), options);

            return RedirectToAction("CheckCookie");
        }

        [HttpGet]
        public IActionResult CheckCookie()
        {
            var cookieValue = Request.Cookies["MyCookie"];
            var cookieExpiry = Request.Cookies["MyCookieExpiry"]; 

            if (string.IsNullOrEmpty(cookieValue))
            {
                ViewBag.Message = "Cookie wasn't found";
            }
            else
            {
                if (string.IsNullOrEmpty(cookieExpiry))
                {
                    ViewBag.Message = $"Value of cookie: {cookieValue}. Expiry date is not set.";
                }
                else
                {
                    ViewBag.Message = $"Value of cookie: {cookieValue}. Expiry date: {cookieExpiry}";
                }
            }

            return View();
        }

        [HttpGet("cause-exception")]
        public IActionResult CauseException()
        {
            throw new Exception("test exception!!");
        }

    }

}

laboratorna5shchedrov/Controllers/HomeController.cs
using laboratorna5shchedrov.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace laboratorna5shchedrov.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

laboratorna5shchedrov/Views/Cookie/CheckCookie.cshtml
@{
    ViewData["Title"] = "Cookie checking";
}

<h2>Checking Cookie</h2>

<p>@ViewBag.Message</p>

laboratorna5shchedrov/Views/Cookie/SetCookie.cshtml
@{
    ViewData["Title"] = "Setting Cookie";
}

<h2>Setting Cookie</h2>

<form method="post">
    <div>
        <label for="value">Value:</label>
        <input type="text" id="value" name="value" />
    </div>
    <div>
        <label for="expiryDate">Date and time of creating:</label>
        <input type="datetime-local" id="expiryDate" name="expiryDate" />
    </div>
    <button type="submit">Set Cookie</button>
</form>

@if (!string.IsNullOrEmpty(ViewBag.Error))
{
    <div style="color: red;">@ViewBag.Error</div>
}

laboratorna5shchedrov/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

laboratorna5shchedrov/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - laboratorna5shchedrov</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/laboratorna5shchedrov.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">laboratorna5shchedrov</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cookie" asp-action="SetCookie">Set Cookie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cookie" asp-action="CheckCookie">Check Cookie</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - laboratorna5shchedrov - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>